In [45]:
import pandas as pd
import sqlite3

In [46]:
df = pd.read_csv("data/superstore.csv", encoding='latin1')
df.head()

,Row ID,Order ID,MONTH ORDERED,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,SubCategory,tegProduct Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,November,Nov-16,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,262,2,0.00,41.9136
1,2,CA-2016-152156,November,Nov-16,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",732,3,0.00,219.5820
2,3,CA-2016-138688,June,Jun-16,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,15,2,0.00,6.8714
3,4,US-2015-108966,October,Oct-15,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,958,5,0.45,-383.0310
4,5,US-2015-108966,October,Oct-15,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22,2,0.20,2.5164

In [47]:
conn = sqlite3.connect("sales.db")
df.to_sql("sales", conn, if_exists="replace", index=False)

9994

In [48]:
query = """
SELECT Region, SUM(Sales) as total_sales
FROM sales
GROUP BY Region
"""

pd.read_sql(query, conn)

    Region  total_sales
0  Central       501256
1     East       678834
2    South       391750
3     West       725514

In [49]:
query = """
SELECT Category, SUM(Profit) as total_profit
FROM sales
GROUP BY Category
ORDER BY total_profit DESC
"""

print(pd.read_sql(query, conn))

          Category  total_profit
0       Technology   145454.9481
1  Office Supplies   122490.8008
2        Furniture    18451.2728

In [50]:
query = """
SELECT SubCategory, SUM(Profit) as total_profit
FROM sales
GROUP BY SubCategory
ORDER BY total_profit ASC
"""

print(pd.read_sql(query, conn))

    SubCategory  total_profit
0        Tables   -17725.4811
1     Bookcases    -3472.5560
2      Supplies    -1189.0995
3     Fasteners      949.5182
4      Machines     3384.7569
5        Labels     5546.2540
6           Art     6527.7870
7     Envelopes     6964.1767
8   Furnishings    13059.1436
9    Appliances    18138.0054
10      Storage    21278.8264
11       Chairs    26590.1663
12      Binders    30221.7633
13        Paper    34053.5693
14  Accessories    41936.6357
15       Phones    44515.7306
16      Copiers    55617.8249

In [51]:
query = """
SELECT "Customer Name", SUM("Sales") as total_sales
FROM sales
GROUP BY "Customer Name"
ORDER BY total_sales DESC
LIMIT 5
"""

print(pd.read_sql(query, conn))

   Customer Name  total_sales
0    Sean Miller        25042
1   Tamara Chand        19050
2   Raymond Buch        15117
3   Tom Ashbrook        14596
4  Adrian Barton        14476

In [52]:
query = """
SELECT * FROM sales
WHERE Region = 'West'
"""

print(pd.read_sql(query, conn).head())

   Row ID        Order ID MONTH  ORDERED Order Date  Ship Date  \
0       3  CA-2016-138688           June     Jun-16  6/16/2016
1       6  CA-2014-115812           June     Jun-14  6/14/2014
2       7  CA-2014-115812           June     Jun-14  6/14/2014
3       8  CA-2014-115812           June     Jun-14  6/14/2014
4       9  CA-2014-115812           June     Jun-14  6/14/2014

        Ship Mode Customer ID    Customer Name    Segment        Country  ...  \
0    Second Class    DV-13045  Darrin Van Huff  Corporate  United States  ...
1  Standard Class    BH-11710  Brosina Hoffman   Consumer  United States  ...
2  Standard Class    BH-11710  Brosina Hoffman   Consumer  United States  ...
3  Standard Class    BH-11710  Brosina Hoffman   Consumer  United States  ...
4  Standard Class    BH-11710  Brosina Hoffman   Consumer  United States  ...

  Postal Code Region       Product ID         Category  SubCategory  \
0       90036   West  OFF-LA-10000240  Office Supplies       Labels
1       90032   West  FUR-FU-10001487        Furniture  Furnishings
2       90032   West  OFF-AR-10002833  Office Supplies          Art
3       90032   West  TEC-PH-10002275       Technology       Phones
4       90032   West  OFF-BI-10003910  Office Supplies      Binders

                                     tegProduct Name Sales Quantity  Discount  \
0  Self-Adhesive Address Labels for Typewriters b...    15        2       0.0
1  Eldon Expressions Wood and Plastic Desk Access...    49        7       0.0
2                                         Newell 322     7        4       0.0
3                     Mitel 5320 IP Phone VoIP phone   907        6       0.2
4  DXL Angle-View Binders with Locking Rings by S...    19        3       0.2

    Profit
0   6.8714
1  14.1694
2   1.9656
3  90.7152
4   5.7825

[5 rows x 22 columns]

In [53]:
query = """
SELECT Region, SUM(Sales) as total_sales, SUM(Profit) as total_profit
FROM sales
GROUP BY Region
ORDER BY total_sales DESC
"""
pd.read_sql(query, conn)

    Region  total_sales  total_profit
0     West       725514   108418.4489
1     East       678834    91522.7800
2  Central       501256    39706.3625
3    South       391750    46749.4303

In [54]:
query = """
SELECT SubCategory, SUM(Sales) as total_sales, SUM(Profit) as total_profit
FROM sales
GROUP BY SubCategory
ORDER BY total_profit ASC
"""
pd.read_sql(query, conn)

    SubCategory  total_sales  total_profit
0        Tables       206968   -17725.4811
1     Bookcases       114879    -3472.5560
2      Supplies        46679    -1189.0995
3     Fasteners         3024      949.5182
4      Machines       189243     3384.7569
5        Labels        12507     5546.2540
6           Art        27137     6527.7870
7     Envelopes        16477     6964.1767
8   Furnishings        91705    13059.1436
9    Appliances       107538    18138.0054
10      Storage       223862    21278.8264
11       Chairs       328454    26590.1663
12      Binders       203428    30221.7633
13        Paper        78475    34053.5693
14  Accessories       167401    41936.6357
15       Phones       330047    44515.7306
16      Copiers       149530    55617.8249

In [55]:
query = """
SELECT Discount, AVG(Profit) as avg_profit
FROM sales
GROUP BY Discount
ORDER BY Discount
"""
pd.read_sql(query, conn)

    Discount  avg_profit
0       0.00   66.900292
1       0.10   96.055074
2       0.15   27.288298
3       0.20   24.702572
4       0.30  -45.679636
5       0.32  -88.560656
6       0.40 -111.927429
7       0.45 -226.646464
8       0.50 -310.703456
9       0.60  -43.077212
10      0.70  -95.874060
11      0.80 -101.796797

In [56]:
query = """
SELECT "Customer Name", SUM("Sales") as total_sales
FROM sales
GROUP BY "Customer Name"
ORDER BY total_sales DESC
LIMIT 5
"""
pd.read_sql(query, conn)

   Customer Name  total_sales
0    Sean Miller        25042
1   Tamara Chand        19050
2   Raymond Buch        15117
3   Tom Ashbrook        14596
4  Adrian Barton        14476

In [57]:
query = """
SELECT strftime('%Y-%m', "Order Date") as month, SUM("Sales") as total_sales
FROM sales
GROUP BY month
ORDER BY month
"""
pd.read_sql(query, conn)

  month  total_sales
0  None      2297354

In [58]:
df["Order Date"] = pd.to_datetime(df["Order Date"], format='mixed', errors='coerce')

In [59]:
print(df["Order Date"].head(10))

0   1-11-16
1   1-11-16
2   1-06-16
3   1-10-15
4   1-10-15
5   1-06-14
6   1-06-14
7   1-06-14
8   1-06-14
9   1-06-14
Name: Order Date, dtype: datetime64[us]

In [60]:
df["Order Date"] = df["Order Date"].dt.strftime('%Y-%m-%d')

In [61]:
df.to_sql("sales", conn, if_exists="replace", index=False)

9994

In [62]:
query = """
SELECT Category,
       SUM(Sales) as total_sales,
       SUM(Profit) as total_profit
FROM sales
GROUP BY Category
ORDER BY total_profit DESC
"""

pd.read_sql(query, conn)

          Category  total_sales  total_profit
0       Technology       836221   145454.9481
1  Office Supplies       719127   122490.8008
2        Furniture       742006    18451.2728

In [63]:
query = """
SELECT `SubCategory`, Category,
       SUM(Sales) as total_sales,
       SUM(Profit) as total_profit
FROM sales
GROUP BY `SubCategory`, Category
ORDER BY total_profit ASC
"""

pd.read_sql(query, conn)

    SubCategory         Category  total_sales  total_profit
0        Tables        Furniture       206968   -17725.4811
1     Bookcases        Furniture       114879    -3472.5560
2      Supplies  Office Supplies        46679    -1189.0995
3     Fasteners  Office Supplies         3024      949.5182
4      Machines       Technology       189243     3384.7569
5        Labels  Office Supplies        12507     5546.2540
6           Art  Office Supplies        27137     6527.7870
7     Envelopes  Office Supplies        16477     6964.1767
8   Furnishings        Furniture        91705    13059.1436
9    Appliances  Office Supplies       107538    18138.0054
10      Storage  Office Supplies       223862    21278.8264
11       Chairs        Furniture       328454    26590.1663
12      Binders  Office Supplies       203428    30221.7633
13        Paper  Office Supplies        78475    34053.5693
14  Accessories       Technology       167401    41936.6357
15       Phones       Technology       330047    44515.7306
16      Copiers       Technology       149530    55617.8249

In [64]:
query = """
SELECT Discount,
       AVG(Profit) as avg_profit
FROM sales
GROUP BY Discount
ORDER BY Discount
"""

pd.read_sql(query, conn)

    Discount  avg_profit
0       0.00   66.900292
1       0.10   96.055074
2       0.15   27.288298
3       0.20   24.702572
4       0.30  -45.679636
5       0.32  -88.560656
6       0.40 -111.927429
7       0.45 -226.646464
8       0.50 -310.703456
9       0.60  -43.077212
10      0.70  -95.874060
11      0.80 -101.796797

In [65]:
query = """
SELECT Region,
       Category,
       SUM(Profit) as total_profit
FROM sales
GROUP BY Region, Category
ORDER BY total_profit DESC
"""

pd.read_sql(query, conn)

     Region         Category  total_profit
0      West  Office Supplies    52609.8490
1      East       Technology    47462.0351
2      West       Technology    44303.6496
3      East  Office Supplies    41014.5791
4   Central       Technology    33697.4320
5     South       Technology    19991.8314
6     South  Office Supplies    19986.3928
7      West        Furniture    11504.9503
8   Central  Office Supplies     8879.9799
9     South        Furniture     6771.2061
10     East        Furniture     3046.1658
11  Central        Furniture    -2871.0494

In [66]:
query="""SELECT State as Top_states  ,Sum(Profit)as Total_Profit from sales group by State order by Total_Profit DESC limit 5"""
pd.read_sql(query,conn)

   Top_states  Total_Profit
0  California    76381.3871
1    New York    74038.5486
2  Washington    33402.6517
3    Michigan    24463.1876
4    Virginia    18597.9504

In [67]:
query="""WITH CategoryTotals AS (
    SELECT 
        SubCategory, 
        SUM(Profit) AS Total_Profit, 
        SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY SubCategory
)
SELECT * 
FROM CategoryTotals
WHERE Total_Profit = (SELECT MIN(Total_Profit) FROM CategoryTotals)
   OR Total_Sales = (SELECT MAX(Total_Sales) FROM CategoryTotals);
"""
pd.read_sql(query, conn)

  SubCategory  Total_Profit  Total_Sales
0      Phones    44515.7306       330047
1      Tables   -17725.4811       206968

In [73]:
query = """
SELECT [Customer Name], SUM(Sales) AS Total_Sales
FROM sales
GROUP BY [Customer Name]
HAVING SUM(Sales) > (
    SELECT AVG(CustomerTotal)
    FROM (
        SELECT SUM(Sales) AS CustomerTotal
        FROM sales
        GROUP BY [Customer Name]
    ) AS SubQuery
)order by Total_Sales DESC Limit 5;

"""
pd.read_sql(query, conn)

   Customer Name  Total_Sales
0    Sean Miller        25042
1   Tamara Chand        19050
2   Raymond Buch        15117
3   Tom Ashbrook        14596
4  Adrian Barton        14476

In [78]:
query = """
SELECT `Region`, SUM(`Sales`) AS Total_Sales,    
       SUM(`Profit`) AS Total_Profit ,
       (SUM(`Profit`)/SUM(`Sales`))*100 as Region_Performance from sales
GROUP BY `Region` Order By Region_Performance DESC"""
pd.read_sql(query,conn)

    Region  Total_Sales  Total_Profit  Region_Performance
0     West       725514   108418.4489           14.943674
1     East       678834    91522.7800           13.482351
2    South       391750    46749.4303           11.933486
3  Central       501256    39706.3625            7.921374